# Generated by Django 5.1.7 on 2025-05-05 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatelearningapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='mobileno',
            new_name='mobile_no',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('business', 'Business'), ('science', 'Science'), ('others', 'Others')], default='programming', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(limit_choices_to={'userdetail__role': 'educator'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('learners', models.ManyToManyField(blank=True, limit_choices_to={'userdetail__role': 'learner'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('coursepage_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(max_length=200)),
                ('page_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('page_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='elevatelearningapp.course')),
            ],
            options={
                'ordering': ['page_no'],
                'unique_together': {('course', 'page_no')},
            },
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('qrcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('qrcode_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='elevatelearningapp.course')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_pages', models.ManyToManyField(blank=True, related_name='completed_by', to='elevatelearningapp.coursepage')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='elevatelearningapp.course')),
                ('current_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_progress', to='elevatelearningapp.coursepage')),
                ('learner', models.ForeignKey(limit_choices_to={'userdetail__role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Progress Records',
                'unique_together': {('learner', 'course')},
            },
        ),
    ]
