# Generated by Django 5.1.7 on 2025-05-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatelearningapp', '0002_rename_mobileno_userdetail_mobile_no_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='elevatelearningapp.coursepage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='elevatelearningapp.coursepage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_page', 'user')},
            },
        ),
    ]
